# Generated by Django 2.2.2 on 2019-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190627_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='postHit',
            field=models.IntegerField(default=0),
        ),
    ]
